/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TAside: typeof import('tdesign-vue-next')['Aside']
    TButton: typeof import('tdesign-vue-next')['Button']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    THeader: typeof import('tdesign-vue-next')['Header']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TSpace: typeof import('tdesign-vue-next')['Space']
  }
}
